import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppHeader from "@/components/AppHeader";
import AppNavigation from "@/components/AppNavigation";
import Providers from "@/providers/Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}  antialiased min-h-full flex flex-col`}
      >
        <Providers>
          <AppHeader />
          <main className="w-full h-full lg:max-w-7xl lg:mx-auto flex flex-col flex-1 p-4 lg:px-0 lg:py-4 gap-4">
            {children}
          </main>
          <AppNavigation />
        </Providers>
      </body>
    </html>
  );
}
